export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	SET_PROJECT: 'SET_PROJECT',
	SET_PROJECTS: 'SET_PROJECTS',
	ADD_PROJECT: 'ADD_PROJECT',
	DELETE_PROJECT: 'DELETE_PROJECT',
	CREATE_TRACK: 'CREATE_TRACK',
	DELETE_TRACK: 'DELETE_TRACK',
	UPDATE_TRACK: 'UPDATE_TRACK',
	RESET_PROJECT_DATA: 'RESET_PROJECT_DATA',
	RESET_PROJECTS_DATA: 'RESET_PROJECTS_DATA',
	SET_OPTIONS: 'SET_OPTIONS',
};
