export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	SET_PROJECT: 'SET_PROJECT',
	SET_PROJECTS: 'SET_PROJECTS',
	ADD_PROJECT: 'ADD_PROJECT',
	DELETE_PROJECT: 'DELETE_PROJECT',
	CREATE_TRECKED_TIME: 'CREATE_TRECKED_TIME',
	DELETE_TRECKED_TIME: 'DELETE_TRECKED_TIME',
	UPDATE_TRECKED_TIME: 'UPDATE_TRECKED_TIME',
	RESET_PROJECT_DATA: 'RESET_PROJECT_DATA',
};
